sudo: required

before_install:
  - docker build -t noirkotyara/sell-server -f ./server/Dockerfile --target development ./server

script:
  - docker run noirkotyara/sell-server npm run test:cov

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "sell-everywhere-server"
  env: "Selleverywhereserver-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-146417388463"
  bucket_path: "sell-everywhere-server"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  on:
    branch: main
