version: '3'

services:
  sell-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
