version: '3'

services:
  nginx:
    image: "noirkotyara/nginx-server"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "3443:80"
    depends_on:
      - sell-client
      - sell-server
  sell-server:
    image: "noirkotyara/sell-server"
    mem_limit: 128m
    hostname: sell-server

  sell-client:
    image: "noirkotyara/sell-client"
    mem_limit: 128m
    hostname: sell-client
