version: '3'

services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "3443:80"
    depends_on:
      - sell-client
      - sell-server
  sell-server:
    build:
      context: ./server
      dockerfile: Dockerfile
  sell-client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: nginxproduction
    command:
      - npm run start
    ports:
      - "2000:3006"

